"""Added some unique contraints

Revision ID: 9be738c770fd
Revises: 8263b99857cc
Create Date: 2024-03-16 01:00:31.692696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be738c770fd'
down_revision: Union[str, None] = '8263b99857cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_blocks_blockhash', table_name='service_blocks')
    op.create_index(op.f('ix_service_blocks_blockhash'), 'service_blocks', ['blockhash'], unique=True)
    op.drop_index('ix_service_inputs_shortcut', table_name='service_inputs')
    op.create_index(op.f('ix_service_inputs_shortcut'), 'service_inputs', ['shortcut'], unique=True)
    op.drop_index('ix_service_outputs_shortcut', table_name='service_outputs')
    op.create_index(op.f('ix_service_outputs_shortcut'), 'service_outputs', ['shortcut'], unique=True)
    op.drop_index('ix_service_transactions_txid', table_name='service_transactions')
    op.create_index(op.f('ix_service_transactions_txid'), 'service_transactions', ['txid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_transactions_txid'), table_name='service_transactions')
    op.create_index('ix_service_transactions_txid', 'service_transactions', ['txid'], unique=False)
    op.drop_index(op.f('ix_service_outputs_shortcut'), table_name='service_outputs')
    op.create_index('ix_service_outputs_shortcut', 'service_outputs', ['shortcut'], unique=False)
    op.drop_index(op.f('ix_service_inputs_shortcut'), table_name='service_inputs')
    op.create_index('ix_service_inputs_shortcut', 'service_inputs', ['shortcut'], unique=False)
    op.drop_index(op.f('ix_service_blocks_blockhash'), table_name='service_blocks')
    op.create_index('ix_service_blocks_blockhash', 'service_blocks', ['blockhash'], unique=False)
    # ### end Alembic commands ###
