"""Added address model

Revision ID: e97ca5f11ed3
Revises: 9be738c770fd
Create Date: 2024-03-16 01:02:34.479546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97ca5f11ed3'
down_revision: Union[str, None] = '9be738c770fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_addresses',
    sa.Column('address', sa.String(length=70), nullable=False),
    sa.Column('balance', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_addresses_address'), 'service_addresses', ['address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_addresses_address'), table_name='service_addresses')
    op.drop_table('service_addresses')
    # ### end Alembic commands ###
